services:
  python:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./python-app:/app
      - ~/Downloads/Youtube_HQ:/downloads  # Mount Host-Ordner in Container
    environment:
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      - DOWNLOAD_PATH=/downloads
      - YDL_CONFIG_DIR=/downloads
      - YDL_OUTPUT_TEMPLATE=/downloads/%(title)s.%(ext)s
      - PYTHONPYCACHEPREFIX=/__pycache__
    restart: always